management:
  endpoints:
    web:
      exposure:
        include: shutdown,health

management:
  endpoint:
    shutdown:
      enabled: true

schalter:
  configItems:
    - item: dev1
    - item: dev2
    - item: dev3

runwith:
  kafka: false

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
#          configuration:
#            auto:
#              offset:
#                reset: earliest

      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json

        greetings-out:
          destination: greetings
          contentType: application/json