schalter:
  items:
    - name: dev1
    - name: dev2
    - name: dev3

runwith:
  kafka: false

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
#          configuration:
#            auto:
#              offset:
#                reset: earliest

      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json

        greetings-out:
          destination: greetings
          contentType: application/json